os: linux
dist: jammy
language: generic
services:
  - docker

git:
  depth: false

env:
  global:
    - DOCKER_IMAGE_NAME=horizenlabs/blockscout-frontend
    - DOCKER_BUILDKIT=1

before_install:
  - docker build --platform=local -o . git://github.com/docker/buildx
  - mkdir -p ~/.docker/cli-plugins
  - mv buildx ~/.docker/cli-plugins/docker-buildx

before_script:
  - source ci/setup_env.sh

jobs:
  include:
    - name: release_image
      script: ci/script.sh
