os: linux
dist: jammy
language: generic
services:
  - docker

git:
  depth: false

env:
  global:
    - DOCKER_IMAGE_NAME=horizenlabs/blockscout-frontend
    - DOCKER_BUILDKIT=1

before_install:
  - ci/setup_docker.sh

before_script:
  - source ci/setup_env.sh

jobs:
  include:
    - name: release_image
      script: ci/script.sh
